### ISSUE TITLE
Clicking "logout" on "please confirm email" screen throws HTTP 405

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [Thiritin/identity#36] opened 2023-02-11 21:42 UTC
(Priority: low)

If you come back to log in before having confirmed your email, the IDP displays a "please confirm your email" screen.

If I click "logout" on this screen, I get an error page

HTTP 405 - The POST method is not supported for route auth/logout. Supported methods: GET, HEAD

**Comment by Thiritin** [comment] 2023-02-11 23:10
duplicate of #24 already resolved and will be included with next release

**Closed by Thiritin** 2023-02-11 23:10 UTC
